### ISSUE TITLE
Disable export?

### ISSUE THREAD

**Issue by dinism** [academic-moodle-cooperation/moodle-local_checkmarkreport#3]
When you have this, and click
![imagem](https://user-images.githubusercontent.com/14828021/36037125-a8e7d38c-0db3-11e8-8773-936725549c44.png)
# I got this. In this situation DISABLE it?
![imagem](https://user-images.githubusercontent.com/14828021/36037188-dbc42abc-0db3-11e8-8be2-09bf0b0dc267.png)

**Comment by goggo24** [comment]
Thanks for reporting - the "userview" tab should be only visible for participants and not for teachers. Because if you open the tab as student, the student himself/herself is selected and the error doesn't occur. The visibility fot the roles can be set by the capability _local/checkmarkreport:view_own_overview_.
You as the administrator see all 3 tabs and of course no user is selected. That's the reason for the bug. We will try to fix the bug in our next minor release.

**Comment by goggo24** [comment]
Exception is solved, there's no error anymore   => v.3.6.0 - coming soon!
