### ISSUE TITLE
No reports are created

### ISSUE THREAD

**Issue by jondo** [academic-moodle-cooperation/moodle-local_checkmarkreport#4]
I am a new user, testing v3.7.0 on Moodle 3.7.x.
I have created two checkmark activities in a course with two students. I let both students do them, then I graded both.
None of the checkmark report tabs now displays any result tables. Instead, nothing happens when I select Update.

Instead, the whole area starting with "Export as" (as seen in the screenshots on https://www.academic-moodle-cooperation.org/en/module/checkmark-report/) stays empty:
![Screenshot_2019-09-17 357 101-10, UE Mathematik 1, Dmitry Efrosinin, Johannes Fürst, Robert Pollak et al , WS 2019 20](https://user-images.githubusercontent.com/21648/65025410-f269eb80-d936-11e9-91ed-1272622b3197.png)

Is the line "There are required fields in this form marked (!)." suspicious? It's not in the official screenshots.

**Comment by goggo24** [comment]
Hey, I just tried it in our own instance and it's working fine. 
Which version of the checkmark report do you use? The parameters in the addional settings are depending on the settings in the checkmark activities. Also the sentence "There are required ...." is correct. We are just updating the plugin infos on moodle.org, because they are not up to date :)
Can you please try it with the debug mode to get further information. Thanks.

**Comment by jondo** [comment]
For some reason the lists are generated now, so I'm closing this issue.

One last remark: I support [this request](https://tracker.moodle.org/browse/MDL-33023) about not always showing the "There are required" warning, especially when the required field is already set. (Also, am I right that the 'exclamation mark in red circle' is not the default symbol configuration?)
